# This file contains fish universal variable definitions.
# VERSION: 3.0
SETUVAR __fish_initialized:3100
SETUVAR _fisher_edc_2F_bass_files:/home/baldi/\x2econfig/fish/functions/__bass\x2epy\x1e/home/baldi/\x2econfig/fish/functions/bass\x2efish
SETUVAR _fisher_jorgebucaran_2F_fisher_files:/home/baldi/\x2econfig/fish/functions/fisher\x2efish\x1e/home/baldi/\x2econfig/fish/completions/fisher\x2efish
SETUVAR _fisher_jorgebucaran_2F_nvm_2E_fish_files:/home/baldi/\x2econfig/fish/functions/_nvm_index_update\x2efish\x1e/home/baldi/\x2econfig/fish/functions/_nvm_list\x2efish\x1e/home/baldi/\x2econfig/fish/functions/_nvm_version_activate\x2efish\x1e/home/baldi/\x2econfig/fish/functions/_nvm_version_deactivate\x2efish\x1e/home/baldi/\x2econfig/fish/functions/nvm\x2efish\x1e/home/baldi/\x2econfig/fish/conf\x2ed/nvm\x2efish\x1e/home/baldi/\x2econfig/fish/completions/nvm\x2efish
SETUVAR _fisher_plugins:jorgebucaran/fisher\x1eedc/bass\x1ejorgebucaran/nvm\x2efish
SETUVAR fish_color_autosuggestion:555
SETUVAR fish_color_cancel:normal
SETUVAR fish_color_command:7dcfff
SETUVAR fish_color_comment:5f5f5f
SETUVAR fish_color_cwd:9ece6a
SETUVAR fish_color_cwd_root:bb9af7
SETUVAR fish_color_end:afd7ff
SETUVAR fish_color_error:f7768e
SETUVAR fish_color_escape:e0af68
SETUVAR fish_color_history_current:normal
SETUVAR fish_color_host:normal
SETUVAR fish_color_host_remote:e0aaf68
SETUVAR fish_color_match:normal
SETUVAR fish_color_normal:c0caf5
SETUVAR fish_color_operator:e0af68
SETUVAR fish_color_param:ffd75f
SETUVAR fish_color_quote:bb9af7
SETUVAR fish_color_redirection:7aa2f7
SETUVAR fish_color_search_match:e0af68
SETUVAR fish_color_selection:414869
SETUVAR fish_color_status:f7768e
SETUVAR fish_color_user:9ece6a
SETUVAR fish_color_valid_path:normal
SETUVAR fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x60help\x60\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish
SETUVAR fish_key_bindings:fish_default_key_bindings
SETUVAR fish_pager_color_completion:normal
SETUVAR fish_pager_color_description:B3A06D\x1eyellow
SETUVAR fish_pager_color_prefix:normal\x1e\x2d\x2dbold\x1e\x2d\x2dunderline
SETUVAR fish_pager_color_progress:brwhite\x1e\x2d\x2dbackground\x3dcyan
SETUVAR fish_user_paths:/home/baldi/\x2elocal/bin\x1e/home/baldi/\x2envm/versions/node/v14\x2e0\x2e0/bin\x1e/Users/baldi/\x2envm/versions/node/v14\x2e0\x2e0/bin\x1e/Users/baldi/\x2enpm\x2dpackages/bin\x1e/home/baldi/\x2efzf/bin
SETUVAR nvm_data:/home/baldi/\x2elocal/share/nvm
SETUVAR nvm_mirror:https\x3a//nodejs\x2eorg/dist
